# Generated by Django 2.2 on 2022-07-01 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_auto_20220630_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='now_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 1, 10, 36, 43, 562342)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 1, 10, 36, 43, 562342)),
        ),
    ]
