# Generated by Django 2.2 on 2022-07-09 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0064_auto_20220709_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradmin',
            name='PIN',
            field=models.IntegerField(default=5194),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 9, 12, 43, 54, 23707)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 9, 12, 43, 54, 23707)),
        ),
    ]
