# Generated by Django 2.2 on 2022-07-11 01:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0066_auto_20220711_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='initial',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 4, 47, 59, 764756)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 4, 47, 59, 764756)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 4, 47, 59, 764756)),
        ),
    ]
