# Generated by Django 2.2 on 2022-07-11 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0068_auto_20220711_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='initial',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 3, 49, 14, 422165)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 3, 49, 14, 418798)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 3, 49, 14, 418832)),
        ),
    ]
