# Generated by Django 2.2 on 2022-07-11 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0069_auto_20220711_0349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradmin',
            name='password',
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='initial',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 6, 45, 41, 453751)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 6, 45, 41, 451386)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 6, 45, 41, 451405)),
        ),
    ]
