# Generated by Django 2.2 on 2022-07-12 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0070_auto_20220711_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='initial',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 8, 50, 0, 30678)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 8, 50, 0, 26645)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 8, 50, 0, 26680)),
        ),
        migrations.AlterField(
            model_name='useradmin',
            name='PIN',
            field=models.CharField(default=5194, max_length=4),
        ),
    ]
