# Generated by Django 2.2 on 2022-07-01 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_auto_20220701_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 1, 21, 46, 15, 224563)),
        ),
    ]
