# Generated by Django 2.2 on 2022-07-02 10:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_auto_20220702_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 13, 34, 22, 803654)),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 13, 34, 22, 803654), editable=False),
        ),
        migrations.CreateModel(
            name='Profits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit_amount', models.IntegerField()),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 7, 2, 13, 34, 22, 803654))),
                ('payment_ref', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.Payment')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
