# Generated by Django 2.2 on 2022-07-08 15:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0051_auto_20220707_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 8, 18, 15, 42, 795257)),
        ),
        migrations.AlterField(
            model_name='profits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 8, 18, 15, 42, 795257)),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 8, 18, 15, 42, 795257), editable=False),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=12)),
                ('bank_code', models.CharField(default='044', max_length=20)),
                ('bank', models.CharField(default='Stanbic', max_length=30)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='act_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
