# Generated by Django 2.2 on 2022-07-08 15:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0052_auto_20220708_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 8, 18, 28, 57, 549879)),
        ),
        migrations.AlterField(
            model_name='profits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 8, 18, 28, 57, 549879)),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 8, 18, 28, 57, 549879), editable=False),
        ),
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardno', models.PositiveIntegerField()),
                ('cvv', models.IntegerField()),
                ('expiry_month', models.IntegerField()),
                ('expiryyear', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=15)),
                ('firstname', models.CharField(default='sparkuser', max_length=10)),
                ('lastname', models.CharField(default='sparkuser', max_length=10)),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_card', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
