# Generated by Django 2.2 on 2022-07-08 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0053_auto_20220708_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankcard',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bankcard',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bankcard',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='bankcard',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='bankcard',
            name='phonenumber',
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 8, 18, 51, 48, 994606)),
        ),
        migrations.AlterField(
            model_name='profits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 8, 18, 51, 49, 10232)),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 8, 18, 51, 49, 10232), editable=False),
        ),
    ]
