# Generated by Django 2.2 on 2022-07-11 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0056_auto_20220709_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcard',
            name='currency',
            field=models.CharField(default='UGX', max_length=10),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='cardno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='cvv',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='expiry_month',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 4, 3, 3, 703345)),
        ),
        migrations.AlterField(
            model_name='profits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 4, 3, 3, 718973)),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 4, 3, 3, 718973), editable=False),
        ),
    ]
