# Generated by Django 2.2 on 2022-07-14 10:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0062_auto_20220712_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 13, 29, 21, 752971)),
        ),
        migrations.AlterField(
            model_name='profits',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 13, 29, 21, 752971)),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 13, 29, 21, 752971), editable=False),
        ),
        migrations.CreateModel(
            name='VirtualAccount',
            fields=[
                ('bvn', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('txRef', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_permanent', models.BooleanField(default=False)),
                ('narration', models.CharField(default='@sparkuser', max_length=100)),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_virtual_acct', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
